---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

version: 1
theme: dark
header:
  - title: XIV Venue Manager
    left:
      - search
    right:
      - clock